name: coconut
description: A project iot

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  http: ^1.1.0
  uuid: ^4.5.1 
  fluttertoast: ^8.2.2  # untuk notifikasi
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  animated_splash_screen: ^1.1.0
  shared_preferences: ^2.2.2
  dot_navigation_bar: ^1.0.2
  intl: ^0.20.2
  google_fonts: ^6.1.0
  flutter_map: ^8.1.1  # untuk menampilkan peta
  latlong2: ^0.9.0
  logging: ^1.2.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/big-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
