// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLFxgzcujRaFF2SFe5CgOtT9l5CxCRQDo',
    appId: '1:273530551047:web:ccb59e50511172651363a2',
    messagingSenderId: '273530551047',
    projectId: 'coconut-iot',
    authDomain: 'coconut-iot.firebaseapp.com',
    storageBucket: 'coconut-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG9MPcX2cOW9pvj8AsjkZoqXM92anP7rY',
    appId: '1:273530551047:android:ee80f932fe954ea31363a2',
    messagingSenderId: '273530551047',
    projectId: 'coconut-iot',
    storageBucket: 'coconut-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeeQpJsMdZJPoXxKSfLlvLnhzPE89rLso',
    appId: '1:273530551047:ios:0e8e5af8a492b1cc1363a2',
    messagingSenderId: '273530551047',
    projectId: 'coconut-iot',
    storageBucket: 'coconut-iot.firebasestorage.app',
    androidClientId: '273530551047-lbiitvots3ocv2lqlcfeio87dnc8f7oh.apps.googleusercontent.com',
    iosClientId: '273530551047-vnldoq1k66g38lha84da0btut0lj1n7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocoApps',
  );
}
